name: build and deploy

on: [push]

jobs: 
  linting:
    name: linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v1
      - name: Install dependencies
        uses: yarn install --frozen-lockfile
      - name: Run linting
        run: yarn run lint 